### ISSUE TITLE
Template Haskell: ByteCodeLink.lookupCE During interactive linking, GHCi couldn't find the following symbol

### ISSUE THREAD

**Issue by ocharles** [haskell/haskell-language-server#1024]
The new Template Haskell support seems to get further at work, now failing with:

```
ghcide version: 0.0.5 (GHC: 8.8.1)
Ghcide setup tester in /home/ollie/work/circuithub.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in /home/ollie/work/circuithub
Found 1 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Loading ./hie.yaml

Step 4/6, Cradle 1/1: Loading GHC Session

Step 5/6: Initializing the IDE

Step 6/6: Type checking the files
ghcide: ^^ Could not load 'filepickerzmpolicyzm0zi2zi6zmLUnJDYkanFc1p7RlDh5zzSr_NetworkziFilepickerziHandle_FilepickerHandle_closure', dependency unresolved. See top entry above.

File:     entities/Model/Common.hs
Range:    1:0-100001:0
Source:   typecheck
Severity: DsError
Message: 
  Program error:
  ByteCodeLink.lookupCE
  During interactive linking, GHCi couldn't find the following symbol:
  filepickerzmpolicyzm0zi2zi6zmLUnJDYkanFc1p7RlDh5zzSr_NetworkziFilepickerziHandle_FilepickerHandle_closure
  This may be due to you not asking GHCi to load extra object files,
  archives or DLLs needed by your current session. Restart GHCi, specifying
  the missing library using the -L/path/to/object/dir and -lmissinglibname
  flags, or simply by naming the relevant files on the GHCi command line.
  Alternatively, this link failure might indicate a bug in GHCi.
  If you suspect the latter, please send a bug report to:
  glasgow-haskell-bugs@haskell.org
ghcide: ^^ Could not load 'OctopartV3ziTypesziCore_Uid_closure', dependency unresolved. See top entry above.

File:     entities/Model/OctopartV3.hs
Range:    1:0-100001:0
Source:   typecheck
Severity: DsError
Message: 
  Program error:
  ByteCodeLink.lookupCE
  During interactive linking, GHCi couldn't find the following symbol:
  OctopartV3ziTypesziCore_Uid_closure
  This may be due to you not asking GHCi to load extra object files,
  archives or DLLs needed by your current session. Restart GHCi, specifying
  the missing library using the -L/path/to/object/dir and -lmissinglibname
  flags, or simply by naming the relevant files on the GHCi command line.
  Alternatively, this link failure might indicate a bug in GHCi.
  If you suspect the latter, please send a bug report to:
  glasgow-haskell-bugs@haskell.org
ghcide: ^^ Could not load 'filepickerzmpolicyzm0zi2zi6zmLUnJDYkanFc1p7RlDh5zzSr_NetworkziFilepickerziHandle_FilepickerHandle_closure', dependency unresolved. See top entry above.

File:     entities/Model/User.hs
Range:    1:0-100001:0
Source:   typecheck
Severity: DsError
Message: 
  Program error:
  ByteCodeLink.lookupCE
  During interactive linking, GHCi couldn't find the following symbol:
  filepickerzmpolicyzm0zi2zi6zmLUnJDYkanFc1p7RlDh5zzSr_NetworkziFilepickerziHandle_FilepickerHandle_closure
  This may be due to you not asking GHCi to load extra object files,
  archives or DLLs needed by your current session. Restart GHCi, specifying
  the missing library using the -L/path/to/object/dir and -lmissinglibname
  flags, or simply by naming the relevant files on the GHCi command line.
  Alternatively, this link failure might indicate a bug in GHCi.
  If you suspect the latter, please send a bug report to:
  glasgow-haskell-bugs@haskell.org
Files that failed:
 * api/src/Daemon/Notification/Consignment.hs
```

My `hie.yaml` is:

```yaml
cradle:
  direct:
    arguments:
      - -Wall
      - -fno-warn-orphans
      - -hide-package resource-pool
      - -hide-package servant-checked-exceptions-core
      - -ich-aws/lib
      - -ich-eda/src
      - -ich-linear/lib
      - -ich-model/lib
      - -ich-persistence/src
      - -ich-segment/lib
      - -ich-servant-auth/lib
      - -ich-stripe/lib
      - -ich-wai-extra/lib
      - -idaemons/ch-shipment-tracking/src
      - -idaemons/ch-sync-mycronic-events/lib
      - -idaemons/ch-sync-trays/lib
      - -ieffects/hedis-simple-effects/lib
      - -ieffects/http-client-simple-effects/lib
      - -ientities
      - -iex-pool-prometheus/lib
      - -imouse-proxy/shared
      - -ioctopart
      - -ipicofactory/aoi/lib
      - -ipicofactory/coordinator/lib
      - -ipicofactory/jpctl/src
      - -ipicofactory/linescan-image-archiver/src
      - -ipicofactory/my300/src
      - -ipicofactory/panelisation/lib
      - -ipicofactory/ur10/lib
      - -ipicofactory/ur10/src-lib
      - -iprelude
      - -iquoting/lib
      - -package-env - # so that .ghci-environment.* generated by cabal is not used
```

The z-encoded name in question comes from something that is in my package database, as witnessed by:

```
$ ghc-pkg dump | grep Network.Filepicker.Handle
Network.Filepicker.Handle Network.Filepicker.Policy
```
