### ISSUE TITLE
ghcide/hie-core: How do I resolve multiple packages with the same module?

### ISSUE THREAD

**Issue by ocharles** [haskell/haskell-language-server#1127]
In my codebase, I have both `resource-pool` and `ex-pool`, but we only really use `ex-pool`. I've tried:

```yaml
cradle:
  direct:
    arguments:
      - -Wall
      - -fno-warn-orphans
      - -hide-package resource-pool-0.2.3.2
```

but I get:

```
File:     ./src/Project/Fork.hs
Range:    32:38-32:47
Source:   not found
Severity: DsError
Message: 
  Could not find module ‘Data.Pool’
  Perhaps you meant
  Data.Pool (from ex-pool-0.2.1)
  Data.Pool (needs flag -package-key resource-pool-0.2.3.2)
  Data.Bool (from base-4.12.0.0)
```

Any idea what I'm missing?
