### ISSUE TITLE
Applying hlint lint causes TypeApplication expressions to turn into holes `_`

### ISSUE THREAD

**Issue by talw** [haskell/haskell-language-server#1242]
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 0.8.0.0 (GHC: 8.10.3) (PATH: /nix/store/px0cwk7xl79yq4b1pvkwaxfkwaswhis1-haskell-language-server-0.8.0.0/bin/haskell-language-server-wrapper)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.5.1
ghc:		8.10.3
```

Which lsp-client do you use:
Neovim
Describe your project (alternative: link to the project):
A cabal project
Contents of `hie.yaml`:
```yaml
cradle:
  cabal:
    - path: "src"
      component: "lib:something"
  direct:
    arguments:
      - -isrc
      - -ionly-for-ghci
      - -XNoImplicitPrelude

      - -XBangPatterns
      - -XBlockArguments
      - -XDataKinds
      - -XDeriveFunctor
      - -XDeriveGeneric
      - -XDerivingStrategies
      - -XExistentialQuantification
      - -XFlexibleContexts
      - -XFlexibleInstances
      - -XFunctionalDependencies
      - -XGeneralizedNewtypeDeriving
      - -XGADTs
      - -XInstanceSigs
      - -XLambdaCase
      - -XMultiParamTypeClasses
      - -XMultiWayIf
      - -XNamedFieldPuns
      - -XNumericUnderscores
      - -XOverloadedStrings
      - -XRank2Types
      - -XRecordWildCards
      - -XScopedTypeVariables
      - -XStandaloneDeriving
      - -XStrictData
      - -XTupleSections
      - -XTypeApplications
      - -XTypeFamilies
      - -XTypeOperators
      - -XTypeSynonymInstances
      - -XViewPatterns
```

### Steps to reproduce
With the following code apply the suggested lint to remove redundant bracket

```haskell
a = (readMaybe @Int content)
```

### Expected behaviour

This appears

```haskell
a = readMaybe @Int content
```

### Actual behaviour

This appears

```haskell
a = _ content
```

This happens in the file so even this:

```haskell
a = readMaybe @Int content

b = (5)
```

Turns into this:

```haskell
a = _ content

b = 5
```

When invoking hlint with apply-refact by themselves through the CLI the
correct behaviour is demonstrated, and so I opened the issue in `haskell-language-server`
and not in `hlint` or `apply-refact`.

The problem seems to be with `TypeApplications`. The extension IS enabled
in hie.yaml's `cradle` -> `direct` -> `arguments` -> `XTypeApplications`

It doesn't matter which hlint lint is applied, as far as I can tell.

**Comment by jneira** [comment]
Many thanks for the detailed report, that is a really ugly bug, will take a look

**Comment by alanz** [comment]
I think there is a `TypeApplications` pragma missing, and the parser is turning the area it can't parse into `_`. I recall hitting this with the ghc-exactprint roundtrip tests for GHC 8.10.3. .

If I put that example into a file Foo.hs I get
```haskell

a = readMaybe @Int content

b = (5)
```
errors

```
 Foo.hs     2   5 error           Pattern syntax in expression context: readMaybe@Int
 Did you mean to enable TypeApplications? (lsp)
 Foo.hs     4   5 info     refact:Redundant bracket Redundant bracket
 Found:
   (5)
 Why not:
   5
 (lsp)
```

**Comment by alanz** [comment]
Related: should there be a code action to enable `TypeApplication`?

**Comment by jneira** [comment]
I cant reproduce with this `hie.yaml`:

```yaml
cradle:
  direct:
    arguments:
      - "-XTypeApplications"
      - "ApplyRefact1"
```

and this `ApplyRefact1.hs`:

```
module ApplyRefact1 where

a = (id @Int 1)
```

hls built from master and ghc-8.10.3 (maybe you are using the released 0.8.0 version?). There had been a big change in the hlint plugin since the 0.8.0 release.
