### ISSUE TITLE
No ghc 8.8.3 support in the haskell-language-server package in nixpkgs

### ISSUE THREAD

**Issue by JonathanLorimer** [haskell/haskell-language-server#1283]
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:
```sh
haskell-language-server version: 0.8.0.0 (GHC: 8.10.3) (PATH: /nix/store/3c6i9fmv0s93q2jymvxd37nb3y2f8bzg-haskell-language-server-0.8.0.0/bin/haskell-language-server-wrapper)
Tool versions found on the $PATH
cabal:		3.0.0.0
stack:		2.5.1.1
ghc:		8.8.3
```
Which lsp-client do you use: Neovim
Describe your project (alternative: link to the project): package.yaml
Contents of `hie.yaml`:
```yaml
cradle:
 cabal:
  - path: "./src"
    component: "lib:mwb"
  - path: "./test"
    component: "test:test"
  - path: "./app"
    component: "exe:mwb"
  - path: "./one-off-task"
    component: "exe:one-off-tasks"
```

I am getting an error that ghcide was compiled with 8.8.4 when my project uses 8.8.3. This is to be expected, but I am wondering if the pre-compiled binaries are missing 8.8.3 support?

running `haskell-language-server-wrapper` shows this: 
```sh
Project GHC version: 8.8.3
haskell-language-server exe candidates: ["haskell-language-server-8.8.3","haskell-language-server-8.8","haskell-language-server"]
Launching haskell-language-server exe at:/etc/profiles/per-user/jonathanl/bin/haskell-language-server-8.8
haskell-language-server version: 0.8.0.0 (GHC: 8.8.4) (PATH: /nix/store/c8709i89qymkcpi6c2b1s3nlmj72b8gz-haskell-language-server-0.8.0.0/bin/haskell-language-server)
```
