### ISSUE TITLE
HLS not displaying type errors when using -Wno-deferred-type-errors

### ISSUE THREAD

**Issue by theGhostJW** [haskell/haskell-language-server#1524]
Initially logged with: [issue 1263](https://github.com/haskell/haskell-language-server/issues/1263#issuecomment-778485721)

### Your environment
**Windows 10 + VS Code + haskell-language-server version: 1.0.0.0 (GHC: 8.10.3)**

Which lsp-client do you use:
 **VSCODE**

Describe your project (alternative: link to the project):
https://github.com/theGhostJW/pyrethrum/releases/tag/Hls_repro_2

Contents of `Package.yaml`:
```yaml
name:                pyrethrum
version:             0.1.0.0
github:              "githubuser/simple-hpack"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/simple-hpack#readme>

dependencies:
  - base
  - containers
  - extra
  - chronos
  - time
  - text
  - transformers-either
  - aeson
  - yaml
  - pretty-show
  - dlist
  - raw-strings-qq
  - polysemy
  - polysemy-plugin

ghc-options:
  - -fmax-pmcheck-models=10000000
  - -ferror-spans
  - -O0
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fplugin=Polysemy.Plugin
  - -fwarn-tabs
  - -fno-warn-unused-imports
  - -fno-warn-missing-signatures
  - -fno-warn-type-defaults
  - -fno-warn-unused-matches
  - -fno-warn-unused-binds
  - -fno-warn-unused-do-bind
  - -fwrite-ide-info

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - ConstrainedClassMethods
  - ConstraintKinds
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - LiberalTypeSynonyms
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

library:
  source-dirs: src
  dependencies:
    - deepseq
    - unordered-containers
    - template-haskell
    - bytestring
    - mtl
    - fmt
```

Contents of `Stack.yaml`:
```yaml
resolver:  nightly-2021-01-01

packages:
- .

allow-newer: true

extra-deps:
- discrimination-0.4@sha256:d42ae36c97ea9c0c8844b47ee162c5530f3daf708636f01010f58dcf52602876,2571
- encode-string-0.1.0.0@sha256:b960508cede9547f5af3ade3d07ed79cbdb575ed128fcac1d7cff0a1162260ce,1864       
- polysemy-1.3.0.0@sha256:fa76e96a883fd1c4bdbad792a0a9d88f59f84817651aea5c71d9b4f74e42c5b6,6141
- polysemy-plugin-0.2.5.1@sha256:61c6c0aad2852377aa5d5a8f9639a437905e3a6f0e2a99a41e96fb231dc86836,2952     
- transformers-either-0.1.1@sha256:ec3d6fefd90e243b51aecebfc0ebc5db6381c261d473ea2df7ed7b501a8fb961,1501
```

Contents of `hie.yaml`:
```yaml
cradle:
  stack:
    stackYaml: "stack.yaml"
```

### Steps to reproduce

Open the linked project VSCode  
> Only warnings displayed

### Expected behaviour
There are numerous type errors in ``Runner.hs`` should be displayed even after deleting %LOCALAPPDATA%\ghcide

### Actual behaviour
> Only warnings displayed

### Include debug information
[hslLog.txt](https://github.com/haskell/haskell-language-server/files/6103420/hslLog.txt)
[stackLog.txt](https://github.com/haskell/haskell-language-server/files/6103424/stackLog.txt)
