### ISSUE TITLE
HLS loops - out of memory? (`Assertion ```freesize < size' failed.`)

### ISSUE THREAD

**Issue by googleson78** [haskell/haskell-language-server#1638]
### hls version
```sh
tauren :: git/benchmark/vray-benchmark-service ‹BENCH-1100_poc*› » haskell-language-server-wrapper --version
haskell-language-server version: 1.0.0.0 (GHC: 8.10.4) (PATH: /home/googleson78/.ghcup/bin/haskell-language-server-wrapper-1.0.0) (GIT hash: 4cd1cf934638881e52b3eba9f70157a4b799c0e9)
```

### Your environment
Describe your project (alternative: link to the project): Private project, can't give link unfortunately
Has 5 components:
* lib
* exe - `generate-data`
* exe - `generate-docs`
* exe - `vray-benchmark-service`
* tests `benchmark-tests`

Contents of `hie.yaml`:
```yaml
cradle:
  stack:
    - path: "./src"
      component: "vray-benchmark-service:lib"

    - path: "./generate-data/Main.hs"
      component: "vray-benchmark-service:exe:generate-data"

    - path: "./generate-data/Paths_vray_benchmark_service.hs"
      component: "vray-benchmark-service:exe:generate-data"

    - path: "./generate-docs/Main.hs"
      component: "vray-benchmark-service:exe:generate-docs"

    - path: "./generate-docs/Paths_vray_benchmark_service.hs"
      component: "vray-benchmark-service:exe:generate-docs"

    - path: "./app/Main.hs"
      component: "vray-benchmark-service:exe:vray-benchmark-service"

    - path: "./app/Paths_vray_benchmark_service.hs"
      component: "vray-benchmark-service:exe:vray-benchmark-service"

    - path: "./tests"
      component: "vray-benchmark-service:test:benchmark-tests"
```

### Steps to reproduce
The file I'm trying to typecheck does not compile - it has a kind mismatch in it.
```haskell
type family ConfigFor (ty :: ScoreType) :: Type where
```
`ScoreType` actually has a type parameter, but In this type family signature it has not been added yet. GHC properly reports this error, and HLS does too (when called directly via a shell), but after failing it just endlessly attempts to recompile again.

### Include debug information
Here's a log of letting hls run until it arbitrarily crashes with an error to stderr (stack overflow error?).
```sh
haskell-language-server-8.8.4: allocatestack.c:384: advise_stack_range: Assertion `freesize < size' failed.
haskell-language-server-wrapper: callProcess: /home/googleson78/.ghcup/bin/haskell-language-server-8.8.4 "-d" "-l" "looping.log" "src/ScoreType.hs" (exit -6): failed
```

I'm including all of the stdout, the stderr, and the output of `-d`, as the stack overflow error seems to not be present in the `-d` output.
[looping.log (`-d` output)](https://github.com/haskell/haskell-language-server/files/6227899/looping.log)
[loopingstdout.log](https://github.com/haskell/haskell-language-server/files/6227897/loopingstdout.log)
[loopingstderr.log](https://github.com/haskell/haskell-language-server/files/6227898/loopingstderr.log)
