### ISSUE TITLE
Spurious errors from extra-project Haskell files.

### ISSUE THREAD

**Issue by friedbrice** [haskell/haskell-language-server#1703]
I have some Haskell files in my project directory outside of the traditional `./src/`, `./app/` and `./test/` directories. Examples are `./dev-tools.hs` where I keep some things I like to use in GHCi, and `./.cache/hie-bios/.../Paths_mwb.hs`.

Haskell plugin reports errors in these files and tries to set up a multi-cradle project, but I would prefer if it didn't since they are not part of my actual project source.

Is there a way to tell the plugin to only trigger for Haskell files in specific directories?

**Comment by fendor** [comment]
Did you try opening the `Paths_` module? That might produce such errors.

I failed to reproduce the issue manually, can you maybe share a project or a minimal example?

**Comment by webdevred** [comment]
Hello, 
I am having similar issues as well, this is my hie.yaml:

```yaml
cradle:
  multi:
    - path: ./examples/ast
      config:
        cradle:
          none:
    - path: ./
      config:
        cradle:
          cabal:
            cabalProject: ./cabal.project.dev
            components:
              - path: ./src
                component: lib:jbeam-edit
              - path: ./src-extra/transformation
                component: jbeam-edit:lib:jbeam-edit-transformation
              - path: ./app
                component: exe:jbeam-edit
              - path: ./tools/dump_ast
                component: exe:jbeam-edit-dump-ast
              - path: ./test
                component: test:jbeam-edit-test
```
https://github.com/webdevred/jbeam_edit/blob/master/hie.yaml

I am getting errror messages whenever opening my AST dumps from my software and I wish I could avoid those errors. I could rename them to something else but I like having the syntax highlighting for them whenever opening the examples. But at same time, since they are generated and intended to be loaded with `read` by my software they will not be able work in HLS. Or am I doing something wrong by calling my AST dumps *.hs?
