### ISSUE TITLE
(Question) Compile errors across multi-cradle projects

### ISSUE THREAD

**Issue by Savelenko** [haskell/haskell-language-server#2035]
I have a general question which seems kind of stupid and trivial, but I did not find any mention of this in documentation. Should code analysis work across different components in a multi-cradle project? Say adding an `Eq` instance in the library project such that an error "immediately" disappears in a test module?

Probably not necessary, but my set-up is VS Code, `stack`, HLS 1.2 and GHC 8.8.4 and an explicit `hie.yaml` with a library, executable and test components.

**Comment by jneira** [comment]
Dont worry, all questions are welcomed and no one is trivial, moreover if you has take a look to docs and did not find a clear answer.
I would say that compile errors across components should work in general, ideally without any restart. I just tried your example and adding the Eq instance in the library removes the type error in the exe component and the other way around.

**Comment by Savelenko** [comment]
Thank you for the answer. I am asking because I started questioning whether my set-up is OK. It seems that I might have a problem somewhere after all as compile errors remain (or do not appear) in my test and executable projects if I make a change in the library. For example, renaming a function in the library is not "visible" in the executable: an error does not appear in the problems pane of VS Code.

`hie.yaml` looks like this:
```
cradle:
  stack:
    - path: "./src"
      component: "haskexp:lib"
    - path: "./app"
      component: "haskexp:exe:haskexp-exe"
    - path: "./test"
      component: "haskexp:test:haskexp-test"
```

Should I be looking somewhere else for the cause of this behavior?
