### ISSUE TITLE
If Project doesn't start in a buildable state HLS doesn't work until at least 1 successful build

### ISSUE THREAD

**Issue by ProofOfKeags** [haskell/haskell-language-server#2174]
Reporting on behalf of Colleague

### Your environment
MacOS, HLS 1.3.0

Which OS do you use:
MacOS
Which lsp-client do you use:
VSCode
Describe your project (alternative: link to the project):
stack + hpack

Contents of `hie.yaml`:
```yaml
cradle:
  stack:
  - path: "./"
    component: "start9-registry:lib"
  - path: "./app"
    component: "start9-registry:exe:start9-registry"
  - path: "./test"
    component: "start9-registry:test:start9-registry-test"
```

### Steps to reproduce
1. Break a project
2. Close all HLS sessions
3. Reopen project in LSP client
4. Watch it cycle over and over again failing to build without reporting errors back into the editor

### Expected behaviour
HLS should work as normal even if the first build fails

### Actual behaviour
No error information will be reported into the editor until HLS can build the project successfully once
