### ISSUE TITLE
segfault loading Cardano.Wallet module in cardano-wallet@2b319e6

### ISSUE THREAD

**Issue by runeksvendsen** [haskell/haskell-language-server#2219]
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:
```sh
haskell-language-server version: 1.4.0.0 (GHC: 8.10.4) (PATH: /Users/rune/Library/Application Support/Code/User/globalStorage/haskell.haskell/haskell-language-server-1.4.0-darwin-8.10.4) (GIT hash: 253547816ee216c53ee7dacc0ad3cac43e863d30)
Tool versions found on the $PATH
cabal:          3.6
stack:          2.5.1
ghc:            8.10.4
```

Which OS do you use: MacOS

Which lsp-client do you use: VS Code
Describe your project (alternative: link to the project): https://github.com/input-output-hk/cardano-wallet/tree/2b319e69b56e2329c3db1295f7dbf1b8b0ff7c91/lib/core
Contents of `hie.yaml`:

(generated by `gen-hie`):

```
cradle:
  cabal:
    - path: "src"
      component: "lib:cardano-wallet-core"

    - path: "test/unit"
      component: "cardano-wallet-core:test:unit"

    - path: "test/shared"
      component: "cardano-wallet-core:test:unit"

    - path: "test/bench/db"
      component: "cardano-wallet-core:bench:db"

    - path: "test/shared"
      component: "cardano-wallet-core:bench:db"

    - path: "test/bench/db/Cardano/Wallet/DummyTarget/Primitive/Types.hs"
      component: "cardano-wallet-core:bench:db"

    - path: "test/shared/Cardano/Wallet/DummyTarget/Primitive/Types.hs"
      component: "cardano-wallet-core:bench:db"
```

### Steps to reproduce

```sh
git clone https://github.com/input-output-hk/cardano-wallet.git
cd cardano-wallet
git checkout 2b319e6
cd lib/core
code .
```

Then, inside VS Code, navigate to the file `src/Cardano/Wallet.hs`.

### Expected behaviour
No error message.

### Actual behaviour
Error message saying: "_The Haskell (core) server crashed 5 times in the last 3 minutes. The server will not be restarted._"

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

* Debug output: https://gist.github.com/runeksvendsen/536420f998f45947cfde692599657724
* LSP logs: https://gist.github.com/runeksvendsen/da45b936b0b6f846dd2d2907a8a8ddb5
