### ISSUE TITLE
How to set up wingman with neovim built in LSP and nvim-lspconfig

### ISSUE THREAD

**Issue by kedashoe** [haskell/haskell-language-server#2334]
### Your environment
```sh
$ haskell-language-server-wrapper --probe-tools
haskell-language-server version: 1.4.0.0 (GHC: 8.10.4) (PATH: /home/kevin/.ghcup/bin/haskell-language-server-wrapper-1.4.0) (GIT hash: 253547816ee216c53ee7dacc0ad3cac43e863d30)
Tool versions found on the $PATH
cabal:		3.6.2.0
stack:		2.7.3
ghc:		9.0.1
```
**Which OS do you use:**
ArchLinux

**Which lsp-client do you use:**
Neovim built in LSP client with nvim-lspconfig

**Describe your project:**
Just testing with default `cabal init` project

**Contents of `hie.yaml`:**
```yaml
$ cat hie.yaml 
cradle:
  cabal:
    - path: "src"
      component: "lib:haskell-wingman-nvim"

    - path: "app/Main.hs"
      component: "haskell-wingman-nvim:exe:haskell-wingman-nvim"
```

### Steps to reproduce
Edit file, run code action on hole, eg
```haskell
myid :: a -> a
myid = _
```

### Expected behaviour *
Get suggestions from wingman

### Actual behaviour
Do not seem to be getting suggestions from wingman. Here is what I see:

![hls](https://user-images.githubusercontent.com/719519/140663899-94a42253-5469-441e-ac5d-d88ed19a1899.png)

### * Notes
I think maybe this is the expected behaviour? It looks like there are instructions for coc.nvim (https://github.com/haskell/haskell-language-server/tree/master/plugins/hls-tactics-plugin#cocnvim) so I guess by default there is more work to do to get wingman support. Has anyone got it working with the built in client and [https://github.com/neovim/nvim-lspconfig](nvim-lspconfig)? And thank you for the great project!
