### ISSUE TITLE
GitHub CI: Deduplicate workflow configuration

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell/haskell-language-server#2422]
After adding https://github.com/haskell/haskell-language-server/pull/2419, workflow configs, platform crutches & matrix'es became shotgun-surgery enough to think about doing the https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#overview work to duplicate in workflows as much as possible.

**Comment by Anton-Latukha** [comment]
At the same time it would be useful to look into: does those `$CABAL*` env variables even need to be set, or the:
```yml
      - name: "Haskell env setup"
        id: HaskEnvSetup
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          
### ...
      - name: "Configuring GitHub cache"
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.HaskEnvSetup.outputs.cabal-store }}
```
is enough (seems enough).
