### ISSUE TITLE
HLS does not respect flags in `stack.yaml`

### ISSUE THREAD

**Issue by re-xyr** [haskell/haskell-language-server#2741]
### Your environment

Which OS do you use: Ubuntu 20.04
Which LSP client (editor/plugin) do you use: vscode

### Steps to reproduce

Create a stack project `my-package`. Add a manual flag that is disabled by default to `package.yaml`, like this:

```yml
flags:
  test:
    description: some description
    manual: true
    default: false
```

Also add some behaviors related to the flag, such as turning on a C++ macro:

```yml
when:
- condition: flag(test)
  cpp-options:
  - -DTEST
```

Now enable the flag in `stack.yaml`

```yml
flags:
  my-package:
    test: true
```

And then write some code in `my-project` that uses the flag:

```haskell
#ifdef TEST
x :: Int
x = 1
#endif
```

### Expected behaviour
The code in the #ifdef block should be compiled by HLS and we should be able to hover on it for type information.

### Actual behaviour

There is no on hover type information, so this chunk of code is not compiled.
