### ISSUE TITLE
"Could not find module" error due to bad cradle root dir

### ISSUE THREAD

**Issue by ratanakkim** [haskell/haskell-language-server#299]
Getting could not find module despite successful build with packages. The module is QuickCheck
![QuickCheck import](https://puu.sh/Gg0Nt/450407c49b.png)
![Failed to find modules](https://puu.sh/Gg0Rv/6cb1efe1dd.png)

package.yaml :
``` yaml
executables:
  wk4-exe:
    main: wk4.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
```
stack.yaml : 
``` yaml
resolver: lts-14.27

packages:
- .

extra-deps: 
- QuickCheck-2.13.2
```
