### ISSUE TITLE
LiquidHaskell is causing HLS to fails 

### ISSUE THREAD

**Issue by ashkann** [haskell/haskell-language-server#3134]
vscode 1.71.0 with Haskell plugin configured to use ghcup +  almost zero code stack project
MacOS
ghc 8.10.7
stack 2.7.5 
HLS 1.7.0.0

Trying to make LiquidHaskell work with the HLS. The `stack build` works so LH setup is well but now LHS outputs an error

```
No 'hie.yaml' found. Try to discover the project type!
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper) Version 1.7.0.0 x86_64 ghc-9.2.2
Current directory: /Users/ashkan/Hobby/Haskell/learn-lh
Operating system: darwin
Arguments: ["--lsp","-d"]
Cradle directory: /Users/ashkan/Hobby/Haskell/learn-lh
Cradle type: Stack

Tool versions found on the $PATH
cabal:		3.6.2.0
stack:		2.7.5
ghc:		8.10.7


Consulting the cradle to get project GHC version...
Project GHC version: 8.10.7
haskell-language-server exe candidates: ["haskell-language-server-8.10.7","haskell-language-server"]
Launching haskell-language-server exe at:/Users/ashkan/.ghcup/tmp/ghcup-ghc-8.10.7_cabal-3.6.2.0_hls-1.7.0.0_stack-2.7.5/haskell-language-server-8.10.7
Failed to get project GHC executable path: CradleError {cradleErrorDependencies = [], cradleErrorExitCode = ExitFailure 1, cradleErrorStderr = ["Error when calling stack exec ghc -- -v0 -package-env=- -ignore-dot-ghci -e Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)","","\n<interactive>:0:1: error:\n    Not in scope: \8216Control.Monad.join\8217\n    No module named \8216Control.Monad\8217 is imported.\n\n<interactive>:0:21: error:\n    Not in scope: \8216Control.Monad.fmap\8217\n    No module named \8216Control.Monad\8217 is imported.\n\n<interactive>:0:40: error:\n    Not in scope: \8216System.IO.putStr\8217\n    No module named \8216System.IO\8217 is imported.\n\n<interactive>:0:57: error:\n    Not in scope: \8216System.Environment.getExecutablePath\8217\n    No module named \8216System.Environment\8217 is imported.\n"]}
[Error - 11:13:30 PM] Connection to server got closed. Server will not be restarted.
[Error - 11:13:30 PM] Notify file events failed.
```

I tried the command on terminal, same error :
```
learn-lh  $> stack exec ghc -- -v0 -package-env=- -ignore-dot-ghci -e "Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)"

<interactive>:0:1: error:
    Not in scope: ‘Control.Monad.join’
    No module named ‘Control.Monad’ is imported.

<interactive>:0:21: error:
    Not in scope: ‘Control.Monad.fmap’
    No module named ‘Control.Monad’ is imported.

<interactive>:0:40: error:
    Not in scope: ‘System.IO.putStr’
    No module named ‘System.IO’ is imported.

<interactive>:0:57: error:
    Not in scope: ‘System.Environment.getExecutablePath’
    No module named ‘System.Environment’ is imported.
```

The minimum to reproduce is to simply add the `liquid-base` (should replace the `base`) :
```
dependencies:
# - base
- liquid-base
# - liquid-vector
# - liquid-containers
# - liquid-bytestring
- liquidhaskell  
```
if I comment out the `liquid-base` and put back the `base` then HLS works but LH integration is crippled (it needs the `liquid-base` to work properly).

the`stack.yaml` file, taken verbatim from `lh-plugin-demo` https://github.com/ucsd-progsys/lh-plugin-demo :
```
allow-newer: true
resolver: lts-18.27
compiler: ghc-8.10.7
packages:
  - .
extra-deps:
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: a4f2198f894810a729feb0f8d06301790ee8d1fb
    subdirs:
      - .
      - liquid-base
      - liquid-prelude
      - liquid-ghc-prim
      # - liquid-containers
      # - liquid-bytestring
      # - liquid-vector
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 08fa6b6e0001c2da6b96a135523ca56107a3c0d6
  - git: https://github.com/facundominguez/rest
    commit: 31e974979c90e910efe5199ee0d3721b791667f6
```

`package.yaml` file :
```
name:                learn-lh
version:             0.1.0.0
github:              "githubuser/learn-lh"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md
description:         Please see the README on GitHub at <https://github.com/githubuser/learn-lh#readme>

dependencies:
# - base
- liquid-base
# - liquid-vector
# - liquid-containers
# - liquid-bytestring
- liquidhaskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fdefer-type-errors -fplugin=LiquidHaskell

library:
  source-dirs:
    - src

executables:
  learn-lh-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learn-lh

tests:
  learn-lh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learn-lh
 ```
 
 Thanks.
