### ISSUE TITLE
Fails to provide Quick Fix(es)

### ISSUE THREAD

**Issue by mouse07410** [haskell/haskell-language-server#3146]
### Your environment

- Which OS do you use? **macOS Monterey 12.5.1**
- Which version of GHC do you use and how did you install it? **All installed via `ghcup`, GHC-9.2.4 and 9.4.2**
- How is your project built (alternative: link to the project)? **Via Cabal-3.8.1.0**
- Which LSP client (editor/plugin) do you use? **VS Codium+vscode-haskell**
- Which version of HLS do you use and how did you install it? **master**
```
ghcup compile his --git-ref master --ghc 9.4.2
ghcup compile his --git-ref master --ghc 9.2.4
```
Have you configured HLS in any way (especially: a `hie.yaml` file)?
```yaml
cradle:
  cabal:
    - path: "src"
      component: "lib:stepic-tests"

    - path: "app/Main.hs"
      component: "stepic-tests:exe:stepic-tests-exe"

    - path: "app/Paths_stepic_tests.hs"
      component: "stepic-tests:exe:stepic-tests-exe"

    - path: "test"
      component: "stepic-tests:test:stepic-tests-test"

    - path: "app/MaybeDemo.hs"
      component: "stepic-tests:exe:maybe-demo"

    - path: "app/Paths_stepic_tests.hs"
      component: "stepic-tests:exe:maybe-demo"
```

### Steps to reproduce

This happens occasionally with GHC-9.2.4, and always with 9.4.2.

Open .hs file in VS Code, edit the source to create "Redundant bracket" situation. E.g.:
```hs
failIndic :: [Maybe a] -> Bool
failIndic = (any isNothing)
```

### Expected behaviour

In the error/warning popup, last line: clickable "View Problem" and clickable "Quick Fix... (Command .)"

### Actual behaviour

In the error/warning popup, last line: clickable "View Problem" and "No quick fixes available"

P.S. I have screenshots, but GitHub decided to deny me the ability to upload them this time. ;-)
