### ISSUE TITLE
Suggesting imports doesn't work on GHC-9.4

### ISSUE THREAD

**Issue by lf-** [haskell/haskell-language-server#3195]
I've seen references to this not working on 9.4 at https://github.com/haskell/haskell-language-server/issues/3187, so I would assume that it's a known issue, but I'm writing it up so it's written down as a limitation.

### Your environment

Which OS do you use?
archlinux/nix

Which version of GHC do you use and how did you install it?
9.4.2 from [a dev branch of nixpkgs](https://github.com/NixOS/nixpkgs/pull/191618)

How is your project built (alternative: link to the project)?
https://github.com/lf-/hsfixit/blob/main/flake.nix [sorry this is not currently buildable due to some hardcoding of the nixpkgs path; however, it is just the branch referenced above]

Which LSP client (editor/plugin) do you use?
neovim+coc

Which version of HLS do you use and how did you install it?
1.8.0.0 from the nix flake in there

Have you configured HLS in any way (especially: a `hie.yaml` file)?

```yaml
cradle:
  cabal:
    - path: "./hsfixit-plugin/src"
      component: "lib:hsfixit-plugin"

    - path: "./hsfixit-types/src"
      component: "lib:hsfixit-types"
```

### Steps to reproduce

Use some identifier that's not in scope, perhaps GHC.Data.Bag.bagToList or similar, and get a compile error.

### Expected behaviour

I would like a code action to import the thing as I get on ghc-9.2.

### Actual behaviour

Seems this doesn't yet happen on 9.4.
