### ISSUE TITLE
Haskell-language-server fails in beam/beam-migrate

### ISSUE THREAD

**Issue by amano-kenji** [haskell/haskell-language-server#3432]
### Your environment

Which OS do you use?
Gentoo Linux
Which version of GHC do you use and how did you install it?
9.0.2 from gentoo haskell overlay
How is your project built (alternative: link to the project)?
https://github.com/haskell-beam/beam

Which LSP client (editor/plugin) do you use?
nvim-lspconfig
Which version of HLS do you use and how did you install it?
1.8.0.0 from gentoo haskell overlay
Have you configured HLS in any way (especially: a `hie.yaml` file)?
No

### Steps to reproduce

Configure neovim with lsp-config. Open any haskell source file in beam/beam-migrate.

### Expected behaviour

No error

### Actual behaviour

```
Diagnostics:
1. Failed to run ["cabal","v2-repl","beam-migrate:lib:is"] in directory "/path/to/beam". Consult the logs for full command and error.
   Failed command: cabal --builddir=$HOME/.cache/hie-bios/dist-beam-7bdef0ed423c2101efa65becf64eb282 v2-repl --with-compiler $HOME/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg $HOME/.cache/hie-bios/ghc-pkg-4f7979c36ba0ad4f82ac0b5533000db1 beam-migrate:lib:is
   
   cabal: Unknown target 'beam-migrate:lib:is'.
   The package beam-migrate has no library component 'is'.

   Process Environment:
   HIE_BIOS_GHC: /usr/lib64/ghc-9.0.2/bin/ghc
   HIE_BIOS_GHC_ARGS: -B/usr/lib64/ghc-9.0.2
```

**Comment by amano-kenji** [comment]
It seems that cabal broke backward compatibility with haskell-language-server.

**Comment by michaelpj** [comment]
We're trying to load a completely nonexistent component, so that's bad. @fendor , any thoughts?

**Comment by fendor** [comment]
Looks like a `implicit-hie` bug, works fine with a `hie.yaml`
```
cradle:
  cabal:
```

**Comment by amano-kenji** [comment]
With
```
cradle:
  cabal:
```
as `hie.yaml`, I can work around the issue, too.

**Comment by amano-kenji** [comment]
I don't have stack on my system, but beam has stack.yaml. Is that why implicit-hie failed?

**Comment by fendor** [comment]
We currently don't know why implicit-hie fails, or why your binary has been built with the affected version of implicit-hie 0.1.3.0, since we have explicitly forbidden that version.

**Comment by amano-kenji** [comment]
My gentoo linux system currently has dev-haskell/implicit-hie-0.1.2.7

**Comment by fendor** [comment]
Reading the report, this does not have to be necessarily connected to the broken release of implicit-hie but an entirely different bug. You can try to reproduce it on the cli by installing the accompaying binary `gen-hie` (should be part of implicit-hie) and running it in your project and inspecting the produced hie.yaml.

**Comment by amano-kenji** [comment]
```
cradle:
  cabal:
    - path: "beam-core/./"
      component: "lib:beam-core"

    - path: "beam-core/test"
      component: "beam-core:test:beam-core-tests"

    - path: "beam-migrate/./"
      component: "beam-migrate:lib:is"

    - path: "beam-migrate/./"
      component: "lib:beam-migrate"

    - path: "beam-migrate-cli/./BeamMigrate.hs"
      component: "beam-migrate-cli:exe:beam-migrate"

    - path: "beam-migrate-cli/./Database/Beam/Migrate/Tool/CmdLine.hs"
      component: "beam-migrate-cli:exe:beam-migrate"

    - path: "beam-migrate-cli/./Database/Beam/Migrate/Tool/Registry.hs"
      component: "beam-migrate-cli:exe:beam-migrate"

    - path: "beam-migrate-cli/./Database/Beam/Migrate/Tool/Backend.hs"
      component: "beam-migrate-cli:exe:beam-migrate"

    - path: "beam-migrate-cli/./Database/Beam/Migrate/Tool/Schema.hs"
      component: "beam-migrate-cli:exe:beam-migrate"

    - path: "beam-migrate-cli/./Database/Beam/Migrate/Tool/MigrationCmd.hs"
      component: "beam-migrate-cli:exe:beam-migrate"

    - path: "beam-migrate-cli/./Database/Beam/Migrate/Tool/Branch.hs"
      component: "beam-migrate-cli:exe:beam-migrate"

    - path: "beam-migrate-cli/./Database/Beam/Migrate/Tool/Database.hs"
      component: "beam-migrate-cli:exe:beam-migrate"

    - path: "beam-migrate-cli/./Database/Beam/Migrate/Tool/Init.hs"
      component: "beam-migrate-cli:exe:beam-migrate"

    - path: "beam-migrate-cli/./Database/Beam/Migrate/Tool/Status.hs"
      component: "beam-migrate-cli:exe:beam-migrate"

    - path: "beam-migrate-cli/./Database/Beam/Migrate/Tool/Diff.hs"
      component: "beam-migrate-cli:exe:beam-migrate"

    - path: "beam-migrate-cli/./Database/Beam/Migrate/Tool/Log.hs"
      component: "beam-migrate-cli:exe:beam-migrate"

    - path: "beam-migrate-cli/./Database/Beam/Migrate/Tool/Migrate.hs"
      component: "beam-migrate-cli:exe:beam-migrate"

    - path: "beam-postgres/./"
      component: "lib:beam-postgres"

    - path: "beam-postgres/test"
      component: "beam-postgres:test:beam-postgres-tests"

    - path: "beam-sqlite/./"
      component: "lib:beam-sqlite"

    - path: "beam-sqlite/test"
      component: "beam-sqlite:test:beam-sqlite-tests"
```
