### ISSUE TITLE
Ability to set custom cabal.project files in hie.yaml

### ISSUE THREAD

**Issue by david-christiansen** [haskell/haskell-language-server#3451]
## Is your enhancement request related to a problem? Please describe.

I was attempting to run HLS on Cabal while contributing a recent PR, and it failed to start and build due to an unsatisfied dependency.

It turns out that local builds from the Cabal git repository require a custom `cabal.project` file, as the default one is for other purposes. That is, running `cabal v2-build Cabal` fails, while `cabal v2-build Cabal --project-file=cabal.project.release` works.

I looked at the docs for `hie.yaml` and couldn't find a way to set this option.

## Describe the solution you'd like

I'd like to be able to have a `hie.yaml` file with the following contents that allows the build to succeed and HLS to work as intended:

```yaml
cradle:
  cabal:
    project-file: "cabal.project.release"
```

with the path being relative to the `hie.yaml` file.

## Describe alternatives you've considered

I haven't thought of any others. One possibility is to just delete the provided cabal.project and symlink cabal.project.release to it, but this is fragile and difficult, and it doesn't help other users have an easy experience.

## Additional context

None.

**Comment by david-christiansen** [comment]
I guess another alternative could be something like:
```yaml
cradle:
  cabal:
    options: ["--project-file=cabal.project.release"]
```
