### ISSUE TITLE
HLS not properly working when configuring XMonad

### ISSUE THREAD

**Issue by reyniersbram** [haskell/haskell-language-server#3553]
## Your environment 

Which OS do you use?
- ArchLinux inside a virtual machine.

Which version of GHC do you use and how did you install it?
- 9.2.7 from stack

Which LSP client (editor/plugin) do you use?
- Neovim

Which version of HLS do you use and how did you install it?
- 1.10.0.0 from ghcup

Have you configured HLS in any way (especially: a `hie.yaml` file)?
- generated hie.yaml with `gen-hie`:
```yaml
cradle:
    stack:
        - path: "xmonad/src"
          component: "xmonad:lib"

        - path: "xmonad/./Main.hs"
          component: "xmonad:exe:xmonad

        - path: "xmonad/tests"
          component: "xmonad:test:properties"

        - path: "xmonad-contrib/./"
          component: "xmonad-contrib:lib"

        - path: "xmonad-contrib/tests"
          component: "xmonad-contrib:test:tests"

        - path: "xmonad-contrib/."
          component: "xmonad-contrib:test:tests"
```

## What's wrong?

I just started to try and use XMonad, but when editing `xmonad.hs` I get the following error:
![image](https://user-images.githubusercontent.com/55666730/229641058-7761a9da-94ae-4524-8a93-b259e793d657.png)
I tried both with and without the generated `hie.yaml` file, without any difference. I tried to do some manual editing of this file as well, but since I didn't really have any idea what I was doing this didn't help either.

I did work on other Haskell projects before with the same neovim setup, but never came across this error.

This is my directory-structure, if this provides some extra usefull information:
![image](https://user-images.githubusercontent.com/55666730/229642322-728c8fd0-b2ac-48ef-967b-b97fcf98be96.png)
The `xmonad` and `xmonad-contrib` directories are just the git repos.

Thanks in advance for the help!
