### ISSUE TITLE
Error with HLS, Stack and Path_* module

### ISSUE THREAD

**Issue by awgn** [haskell/haskell-language-server#478]
Hi there,

It seems that after the latest update, HLS no longer works with my stack projects. 

No matter if I create the configuration manually or if I use gen-hie supplying hie.yaml file. I always get the following error shown in vscode problems window:
 
```
Multi Cradle: No prefixes matched
pwd: /Users/admin/GitLab/Horta
filepath: /Users/admin/GitLab/Horta/src/Main.hs
prefixes:
("./src/Main.hs", Stack {component = Just "horta:exe:horta", stackYaml = Nothing})
...
```

After this the plugin does not work, mouse over does not resolve types, etc.

### My Environment

```
/Users/admin/Library/Application\ Support/Code/User/globalStorage/haskell.haskell/haskell-language-server-0.5.0-darwin-8.8.3 --probe-tools
haskell-language-server version: 0.5.0.0 (GHC: 8.8.3) (PATH: /Users/admin/Library/Application Support/Code/User/globalStorage/haskell.haskell/haskell-language-server-0.5.0-darwin-8.8.3) (GIT hash: 14497f2503a2a0d389fabf3b146d674b9af41a34)
Tool versions found on the $PATH
cabal:          2.4.1.0
stack:          2.3.3
ghc:            Not found
```

* Visual Studio Code for MacOS

* stack.yaml
```
resolver: lts-15.13
packages:
- '.'

extra-deps: 
- bounded-tchan-0.2.3
- vector-strategies-0.4
- git: https://github.com/haskell-works/hw-kafka-client.git 
  commit: 2d33327f94802048aeb6b5818db381edca544db7  # master
- './vegoia-tree-lib'
- './vegoia-label'

# Override default flag values for local packages and extra-deps
flags:
   aeson:
     cffi: true

# Extra package databases containing global packages
extra-package-dbs: []

extra-include-dirs:
- /usr/local/opt/openssl/include
  
extra-lib-dirs: 
-  /usr/local/opt/openssl/lib 
-  /usr/local/lib
-  ./lib 

rebuild-ghc-options: true
```

* horta.cabal

```
name:                horta
version:             3.24.1
-- synopsis:
-- description:
homepage:            https://github.com/githubuser/horta#readme
license-file:        LICENSE
author:              Author name here
maintainer:          nicola.bonelli@larthia.com
copyright:           2018 Nicola Bonelli
category:            Web
build-type:          Simple
cabal-version:       >=1.10
extra-source-files:  README.md 

flag UseLicense {
    Description: "Compile with lasa license"
    Default: False
}

executable horta
  hs-source-dirs:      src
  main-is:             Main.hs
  other-modules:      
                       Horta.Icmp
                       Horta.Flow
                       Horta.Event
                       Horta.Flow.Aeson
                       Horta.SmallFlow
                       Horta.StandardFlow
                       Horta.Ingester
                       ...
  default-language:    Haskell2010
  build-depends:       base >= 4.7 && < 5
                     , optparse-applicative
                     , safe
                     , safe-exceptions
                     , unordered-containers
                     , http-streams
                     , bytestring
                     , deepseq 
                     , text
                     , text-show
                     , split
                     , io-streams
                     , binary
                     , yaml
                     , scotty
                     , aeson
                     ....
                     
  Ghc-options:  -O2 
                -Wall 
                -Wmissing-deriving-strategies
                -funbox-strict-fields 
                -fwrite-ide-info 
                -hiedir=.hie
                -threaded 
                -rtsopts "-with-rtsopts=-N -qm -H1g -M2g" 

    extra-libraries:    rdkafka 

```

Thanks,
Nicola

**Comment by googleson78** [comment]
You should try the lastest stack RC (2.5) - can't tell from your description, but if you're using `Paths_*` modules, you won't be able to load them without it.

**Comment by awgn** [comment]
Indeed, I'm using Paths_ modules, and yes upgrading to the stack v2.5.0.1 (release candidate) it works!

Thanks!

**Comment by googleson78** [comment]
See this issue if you're interested in more info - https://github.com/haskell/ghcide/issues/819

**Comment by awgn** [comment]
Update:

while upgrading stack to version 2.5.0.1 fixes the problem in the majority of my stack projects, in some (in which Path_ module is used) the issue persists. 

This happens also with the most recent version of HLS (0.5.1). 

Yet, no matter if I provide the hie.yaml or not. I always get the same error:

```
Multi Cradle: No prefixes matched
pwd: /Users/admin/GitLab/Horta
filepath: /Users/admin/GitLab/Horta/src/Main.hs
prefixes:
("./src/Main.hs", Stack {component = Just "horta:exe:horta", stackYaml = Nothing})
...
```

Any suggestion to work around this?
N.

**Comment by googleson78** [comment]
What's your hie.yaml, and what's your project? If you could share both somewhere (as a reproducer) that would be great!

**Comment by awgn** [comment]
Unfortunately, I can't share the repository of the project is private. 

However, the cradle is very simple:

```
cradle:
  stack:
    - path: "./src/Main.hs"
      component: "horta:exe:horta"

    - path: "./src/Vegoia.VFlow.hs"
      component: "horta:exe:horta"

    - path: "./src/Vegoia.VFlow.Aeson.hs"
      component: "horta:exe:horta"

    - path: "./src/Vegoia.VFlow.Serialise.hs"
      component: "horta:exe:horta"

    - path: "./src/Vegoia.Anomaly.hs"
      component: "horta:exe:horta"

    - path: "./src/Vegoia.ModFilters.hs"
      component: "horta:exe:horta"

    - path: "./src/Vegoia.Modbus.hs"
      component: "horta:exe:horta"

    - path: "./src/Vegoia.Http.hs"
      component: "horta:exe:horta"

    - path: "./src/Vegoia.Events.hs"
      component: "horta:exe:horta"

    - path: "./src/Vegoia.S3.hs"
      component: "horta:exe:horta"
      ...
```

The stack project, in addition to Path_ module, makes use of a couple of libraries as git submodules:

```
resolver: lts-15.13

packages:
- '.'

extra-deps:
- bounded-tchan-0.2.3
- vector-strategies-0.4
- './vegoia-lib'
- './vegoia-label'

# Override default flag values for local packages and extra-deps
flags:
   aeson:
     cffi: true

# Extra package databases containing global packages
extra-package-dbs: []

extra-include-dirs:
- /usr/local/opt/openssl/include

extra-lib-dirs:
-  /usr/local/opt/openssl/lib
-  /usr/local/lib
-  ./lib

rebuild-ghc-options: true
```

The cabal:

```
...
executable horta
  hs-source-dirs:      src
  main-is:             Main.hs
  other-modules:       Vegoia.VFlow
                       Vegoia.VFlow.Aeson
                       Vegoia.VFlow.Serialise
                       Vegoia.Anomaly
                       Vegoia.ModFilters
                       Vegoia.Modbus
                       Vegoia.Http
                       Vegoia.Events
                       ...
                       Paths_horta
                       Logger
                       Crypto
                       Murmur
                       Horta
                       Pretty
                       Util
 default-language:    Haskell2010
  build-depends:       base >= 4.7 && < 5
                     , optparse-applicative
                     , safe
                     , safe-exceptions
                     , unordered-containers
                     , http-streams
                     , bytestring
                     , deepseq
                     , text
                     , text-show
                     , split
                     , io-streams
                     , binary
                     , yaml
                      ...
 Ghc-options:  -O2
                -Wall
                -Wmissing-deriving-strategies
                -funbox-strict-fields
                -fwrite-ide-info
                -hiedir=.hie
                -threaded
                -rtsopts "-with-rtsopts=-N -qm -H1g -M2g"
```

Hope this info can be of help.
N.
