### ISSUE TITLE
Applying hlint deindents where clause and remove comments

### ISSUE THREAD

**Issue by srid** [haskell/haskell-language-server#597]
Applying a hlint fix messes up the `where` block in the function. See gif screenshot below.

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
./haskell-language-server-8.8.4 --probe-tools
haskell-language-server version: 0.6.0.0 (GHC: 8.8.4) (PATH: /home/srid/.local/bin/haskell-language-server-8.8.4) (GIT hash: 61c69fd387281c2222f75f13542eaa2e91cbc1b1)
Tool versions found on the $PATH
cabal:		Not found
stack:		2.5.1
ghc:		Not found

```
Which lsp-client do you use:

VSCode w/ http://github.com/srid/neuron (Markdown.hs)

Contents of `hie.yaml`:
```yaml
cradle:
  cabal:
    - path: "./neuron/src/lib"
      component: "lib:neuron"
    - path: "./neuron/src/app"
      component: "lib:neuron-app-lib"
    - path: "./neuron/src/exe"
      component: "exe:neuron"
    - path: "./neuron/test"
      component: "test:neuron-test"

```

### Steps to reproduce
1. Open Markdown.hs in neuron repo
2. Apply eta reduction hlint for `partitionMarkdown`

### Expected behaviour
only hlint is applied

### Actual behaviour
where clause gets deindented. see gif attachment.
![hls-wherebug](https://user-images.githubusercontent.com/3998/99104476-08148880-25af-11eb-8a1b-443e066d8bed.gif)

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

<details>
<summary>
Debug output:
</summary>

```
<paste your logs here>
```
</details>

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
LSP logs:
</summary>

```
<paste your logs here>
```
</details>
