### ISSUE TITLE
cabal: 'repl' doesn't take any extra arguments when outside a project

### ISSUE THREAD

**Issue by codygman** [haskell/haskell-language-server#894]
ghcide 2 is working fine for me from NixOS using direnv. My teammates trying to run from ubuntu+nix+direnv are getting an error. I reproduced the error from a fresh ubuntu vm:

```
Failed to parse result of calling cabal
  
cabal: 'repl' doesn't take any extra arguments when outside a project: test
```

So for some reason ghcide is invoking `cabal repl` from somewhere that's not a project? Here is my hie.yaml:

```
cradle:
  multi:
    - path: "./library"
      config: { cradle: {cabal: {component: "lib:smurf"}} }
    - path: "./test"
      config: { cradle: {cabal: {component: "test"}} }
```

# Version information
 vscode plugins:
arrterian.nix-env-selector@0.1.2
DigitalAssetHoldingsLLC.ghcide@0.0.2
justusadam.language-haskell@3.2.1

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-33-generic, Ubuntu, 20.04 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(cody): `"nixpkgs-20.09pre228333.1ae28ebfdb7, home-manager"`
 - nixpkgs: `/home/cody/.nix-defexpr/channels/nixpkgs`
